services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app:latest
    container_name: my_node_app_container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules